### PR TITLE
Peer code review pull request

### PR DESCRIPTION
**Pull request by optimusinhisprime**

### CODE REVIEW

**Comment by loitijoseph** [comment]
Well structured. Consider centering the button...

**Comment by ChinyangaTL** [comment]
Just wondering about the choices you made in terms of placing js functions in the HTML. 
But otherwise, it's clean and concise.

**Comment by optimusinhisprime** [comment]
I separated the js & html and added it in the js file. When i need a function i call the function from index.js in index.html.

**Comment by rmoswela** [comment]
thanks @ChinyangaTL and @loitijoseph for the comments. It shows you followed the instructions. And well done @iseeflames

**Pull request merged**
